#!/usr/bin/env bash
# a script that configures a  my new Ubuntu 
# server machine to respect the requirements


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
